package st.tiy.voidapp.model.dto.match;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class DtoChallenges {
	private Integer assistStreakCount12;
	private Integer healFromMapSources;
	private Integer infernalScalePickup;
	private Integer sWARMDefeatAatrox;
	private Integer sWARMDefeatBriar;
	private Integer sWARMDefeatMiniBosses;
	private Integer sWARMEvolveWeapon;
	private Integer sWARMHave3Passives;
	private Integer sWARMKillEnemy;
	private Integer sWARMPickupGold;
	private Integer sWARMReachLevel50;
	private Integer sWARMSurvive15Min;
	private Integer sWARMWinWith5EvolvedWeapons;
	private Integer abilityUses;
	private Integer acesBefore15Minutes;
	private Integer alliedJungleMonsterKills;
	private Integer baronTakedowns;
	private Integer blastConeOppositeOpponentCount;
	private Integer bountyGold;
	private Integer buffsStolen;
	private Integer completeSupportQuestInTime;
	private Integer controlWardsPlaced;
	private Double damagePerMinute;
	private Double damageTakenOnTeamPercentage;
	private Integer dancedWithRiftHerald;
	private Integer deathsByEnemyChamps;
	private Integer dodgeSkillShotsSmallWindow;
	private Integer doubleAces;
	private Integer dragonTakedowns;
	private Integer earlyLaningPhaseGoldExpAdvantage;
	private Integer effectiveHealAndShielding;
	private Integer elderDragonKillsWithOpposingSoul;
	private Integer elderDragonMultikills;
	private Integer enemyChampionImmobilizations;
	private Integer enemyJungleMonsterKills;
	private Integer epicMonsterKillsNearEnemyJungler;
	private Integer epicMonsterKillsWithin30SecondsOfSpawn;
	private Integer epicMonsterSteals;
	private Integer epicMonsterStolenWithoutSmite;
	private Integer firstTurretKilled;
	private Integer fistBumpParticipation;
	private Integer flawlessAces;
	private Integer fullTeamTakedown;
	private Double gameLength;
	private Integer getTakedownsInAllLanesEarlyJungleAsLaner;
	private Double goldPerMinute;
	private Integer hadOpenNexus;
	private Integer immobilizeAndKillWithAlly;
	private Integer initialBuffCount;
	private Integer initialCrabCount;
	private Integer jungleCsBefore10Minutes;
	private Integer junglerTakedownsNearDamagedEpicMonster;
	private Integer kTurretsDestroyedBeforePlatesFall;
	private Integer kda;
	private Integer killAfterHiddenWithAlly;
	private Integer killParticipation;
	private Integer killedChampTookFullTeamDamageSurvived;
	private Integer killingSprees;
	private Integer killsNearEnemyTurret;
	private Integer killsOnOtherLanesEarlyJungleAsLaner;
	private Integer killsOnRecentlyHealedByAramPack;
	private Integer killsUnderOwnTurret;
	private Integer killsWithHelpFromEpicMonster;
	private Integer knockEnemyIntoTeamAndKill;
	private Integer landSkillShotsEarlyGame;
	private Integer laneMinionsFirst10Minutes;
	private Integer laningPhaseGoldExpAdvantage;
	private Integer legendaryCount;
	private List<Integer> legendaryItemUsed;
	private Integer lostAnInhibitor;
	private Integer maxCsAdvantageOnLaneOpponent;
	private Integer maxKillDeficit;
	private Integer maxLevelLeadLaneOpponent;
	private Integer mejaisFullStackInTime;
	private Integer moreEnemyJungleThanOpponent;
	private Integer multiKillOneSpell;
	private Integer multiTurretRiftHeraldCount;
	private Integer multikills;
	private Integer multikillsAfterAggressiveFlash;
	private Integer outerTurretExecutesBefore10Minutes;
	private Integer outnumberedKills;
	private Integer outnumberedNexusKill;
	private Integer perfectDragonSoulsTaken;
	private Integer perfectGame;
	private Integer pickKillWithAlly;
	private Integer playedChampSelectPosition;
	private Integer poroExplosions;
	private Integer quickCleanse;
	private Integer quickFirstTurret;
	private Integer quickSoloKills;
	private Integer riftHeraldTakedowns;
	private Integer saveAllyFromDeath;
	private Integer scuttleCrabKills;
	private Integer skillshotsDodged;
	private Integer skillshotsHit;
	private Integer snowballsHit;
	private Integer soloBaronKills;
	private Integer soloKills;
	private Integer stealthWardsPlaced;
	private Integer survivedSingleDigitHpCount;
	private Integer survivedThreeImmobilizesInFight;
	private Integer takedownOnFirstTurret;
	private Integer takedowns;
	private Integer takedownsAfterGainingLevelAdvantage;
	private Integer takedownsBeforeJungleMinionSpawn;
	private Integer takedownsFirstXMinutes;
	private Integer takedownsInAlcove;
	private Integer takedownsInEnemyFountain;
	private Integer teamBaronKills;
	private Double teamDamagePercentage;
	private Integer teamElderDragonKills;
	private Integer teamRiftHeraldKills;
	private Integer tookLargeDamageSurvived;
	private Integer turretPlatesTaken;
	private Integer turretTakedowns;
	private Integer turretsTakenWithRiftHerald;
	private Integer twentyMinionsIn3SecondsCount;
	private Integer twoWardsOneSweeperCount;
	private Integer unseenRecalls;
	private Double visionScoreAdvantageLaneOpponent;
	private Double visionScorePerMinute;
	private Integer voidMonsterKill;
	private Integer wardTakedowns;
	private Integer wardTakedownsBefore20M;
	private Integer wardsGuarded;
}
