package st.tiy.budgetopgg.model.riot.match;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;

@Getter
@Setter
public class Challenges {
	@JsonProperty("12AssistStreakCount")
	private int _12AssistStreakCount;
	@JsonProperty("InfernalScalePickup")
	private int infernalScalePickup;
	private int SWARM_DefeatAatrox;
	private int SWARM_DefeatBriar;
	private int SWARM_DefeatMiniBosses;
	private int SWARM_EvolveWeapon;
	private int SWARM_Have3Passives;
	private int SWARM_KillEnemy;
	private int SWARM_PickupGold;
	private int SWARM_ReachLevel50;
	private int SWARM_Survive15Min;
	private int SWARM_WinWith5EvolvedWeapons;
	private int abilityUses;
	private int acesBefore15Minutes;
	private int alliedJungleMonsterKills;
	private int baronTakedowns;
	private int blastConeOppositeOpponentCount;
	private int bountyGold;
	private int buffsStolen;
	private int completeSupportQuestInTime;
	private int controlWardsPlaced;
	private int damagePerMinute;
	private double damageTakenOnTeamPercentage;
	private int dancedWithRiftHerald;
	private int deathsByEnemyChamps;
	private int dodgeSkillShotsSmallWindow;
	private int doubleAces;
	private int dragonTakedowns;
	private int effectiveHealAndShielding;
	private int elderDragonKillsWithOpposingSoul;
	private int elderDragonMultikills;
	private int enemyChampionImmobilizations;
	private int enemyJungleMonsterKills;
	private int epicMonsterKillsNearEnemyJungler;
	private int epicMonsterKillsWithin30SecondsOfSpawn;
	private int epicMonsterSteals;
	private int epicMonsterStolenWithoutSmite;
	private int firstTurretKilled;
	private int fistBumpParticipation;
	private int flawlessAces;
	private int fullTeamTakedown;
	private double gameLength;
	private int getTakedownsInAllLanesEarlyJungleAsLaner;
	private double goldPerMinute;
	private int hadOpenNexus;
	private int immobilizeAndKillWithAlly;
	private int initialBuffCount;
	private int initialCrabCount;
	private int jungleCsBefore10Minutes;
	private int junglerTakedownsNearDamagedEpicMonster;
	private int kTurretsDestroyedBeforePlatesFall;
	private int kda;
	private int killAfterHiddenWithAlly;
	private int killedChampTookFullTeamDamageSurvived;
	private int killingSprees;
	private int killsNearEnemyTurret;
	private int killsOnOtherLanesEarlyJungleAsLaner;
	private int killsOnRecentlyHealedByAramPack;
	private int killsUnderOwnTurret;
	private int killsWithHelpFromEpicMonster;
	private int knockEnemyIntoTeamAndKill;
	private int landSkillShotsEarlyGame;
	private int laneMinionsFirst10Minutes;
	private int legendaryCount;
	private ArrayList<Integer> legendaryItemUsed;
	private int lostAnInhibitor;
	private int maxKillDeficit;
	private int mejaisFullStackInTime;
	private int moreEnemyJungleThanOpponent;
	private int multiKillOneSpell;
	private int multiTurretRiftHeraldCount;
	private int multikills;
	private int multikillsAfterAggressiveFlash;
	private int outerTurretExecutesBefore10Minutes;
	private int outnumberedKills;
	private int outnumberedNexusKill;
	private int perfectDragonSoulsTaken;
	private int perfectGame;
	private int pickKillWithAlly;
	private int poroExplosions;
	private int quickCleanse;
	private int quickFirstTurret;
	private int quickSoloKills;
	private int riftHeraldTakedowns;
	private int saveAllyFromDeath;
	private int scuttleCrabKills;
	private int skillshotsDodged;
	private int skillshotsHit;
	private int snowballsHit;
	private int soloBaronKills;
	private int soloKills;
	private int stealthWardsPlaced;
	private int survivedSingleDigitHpCount;
	private int survivedThreeImmobilizesInFight;
	private int takedownOnFirstTurret;
	private int takedowns;
	private int takedownsAfterGainingLevelAdvantage;
	private int takedownsBeforeJungleMinionSpawn;
	private int takedownsFirstXMinutes;
	private int takedownsInAlcove;
	private int takedownsInEnemyFountain;
	private int teamBaronKills;
	private int teamElderDragonKills;
	private int teamRiftHeraldKills;
	private int tookLargeDamageSurvived;
	private int turretPlatesTaken;
	private int turretTakedowns;
	private int turretsTakenWithRiftHerald;
	private int twentyMinionsIn3SecondsCount;
	private int twoWardsOneSweeperCount;
	private int unseenRecalls;
	private int visionScorePerMinute;
	private int voidMonsterKill;
	private int wardTakedowns;
	private int wardTakedownsBefore20M;
	private int wardsGuarded;
}
