spring:
  application:
    name: Void
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: ERROR
    st:
      tiy: ERROR