spring:
  application:
    name: Void
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

voidapp:
  mastery:
    count: 4
  cleanup:
    enabled: true
    cutoff-days: 30
    cron: 0 0 2 * * ?
  update:
    enabled: true
    delay: 2 # Update summoner delay in minutes
