spring:
  application:
    name: Void
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true

management:
  endpoints:
    web:
      exposure:
        include: health