api:
  key:

spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: dev
    password: ved

logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: INFO
    st:
      tiy: INFO