api:
  key:

spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: dev
    password: ved
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org:
      hibernate: INFO
      springframework:
        web: INFO
    st:
      tiy: INFO

voidapp:
  cleanup:
    enabled: false
    cutoff-days: 0
    cron: 0 */3 * * * *
  update:
    enabled: false
    delay: 2
  processingQueue:
    basicSummonerFetch: false
