api:
  key: ${API_KEY}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: INFO
    st:
      tiy: INFO
    root: INFO

voidapp:
  cleanup:
    enabled: true
    cutoff-days: 21
    cron: 0 0 4 * * ?
  update:
    enabled: true
    delay: 2 # Update summoner delay in minutes
  processingQueue:
    fixedDelay: 10000 # Delay between finished task 1 and start task 2
    basicSummonerFetch: true
