name: Build and Test Java Project

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission to Gradle
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew test --continue

    - name: Build with Gradle
      run: ./gradlew build --continue